### PR TITLE
Fix/new no utils

### LINKED ISSUE #79: this.utils is not defined
https://github.com/trufflesuite/drizzle-react-components/blob/f8592a1a76989f759aefc9e9c746dc204a65f4ff/src/new-context-api/ContractForm.js#L40

### PR DESCRIPTION
**Pull request by honestbonsai**
Fixes #79

### CODE REVIEW

File: src/new-context-api/ContractForm.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ class ContractForm extends Component {
     this.handleSubmit = this.handleSubmit.bind(this);
 
     this.contracts = props.drizzle.contracts;
+    this.utils = props.drizzle.web3.utils;
```
Comment (honestbonsai) [inline src/new-context-api/ContractForm.js:12]: It's really just this line. The rest is because of prettier.

**Review by adrianmcli — APPROVED** [review]
